name = "tera-bomber"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[durable_objects.bindings]]
name = "GAME_STATE"
class_name = "GameState"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameState"]
